# Generated by Django 5.0 on 2025-11-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color_id',
            field=models.CharField(blank=True, help_text='Google Calendar color ID (1-11)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='guest_emails',
            field=models.TextField(blank=True, help_text='Comma-separated list of guest email addresses', null=True),
        ),
    ]
