# Generated by Django 5.0 on 2025-11-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('llm_provider', models.CharField(choices=[('openai', 'OpenAI')], default='openai', help_text='The LLM provider to use for parsing text into events', max_length=50)),
                ('llm_model', models.CharField(default='gpt-4', help_text='The specific model to use (e.g., gpt-4, gpt-3.5-turbo)', max_length=100)),
                ('llm_api_key', models.CharField(blank=True, help_text='API key for the LLM provider. Leave empty to use environment variable OPENAI_API_KEY.', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
