# Generated by Django 5.0 on 2025-11-05 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_systemsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='llm_api_key',
            field=models.CharField(blank=True, help_text='API key for the LLM provider. Leave empty to use environment variable OPENAI_API_KEY.', max_length=500, verbose_name='LLM API Key'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='llm_model',
            field=models.CharField(default='gpt-4', help_text='The specific model to use (e.g., gpt-4, gpt-3.5-turbo)', max_length=100, verbose_name='LLM Model'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='llm_provider',
            field=models.CharField(choices=[('openai', 'OpenAI')], default='openai', help_text='The LLM provider to use for parsing text into events', max_length=50, verbose_name='LLM Provider'),
        ),
        migrations.CreateModel(
            name='LLMParsingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(help_text='Original text input that was parsed')),
                ('input_text_length', models.IntegerField(help_text='Length of input text in characters')),
                ('llm_provider', models.CharField(help_text='LLM provider used (e.g., openai)', max_length=50)),
                ('llm_model', models.CharField(help_text='LLM model used (e.g., gpt-4)', max_length=100)),
                ('success', models.BooleanField(default=False, help_text='Whether parsing was successful')),
                ('response_time_ms', models.FloatField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('error_type', models.CharField(blank=True, choices=[('json_decode', 'JSON Decode Error'), ('missing_field', 'Missing Required Field'), ('api_error', 'API Error'), ('timeout', 'Timeout'), ('rate_limit', 'Rate Limit'), ('auth_error', 'Authentication Error'), ('other', 'Other Error')], help_text='Type of error if parsing failed', max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if parsing failed', null=True)),
                ('parsed_data', models.JSONField(blank=True, help_text='Parsed event data if successful', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who made the parsing request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_parsing_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LLM Parsing Log',
                'verbose_name_plural': 'LLM Parsing Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='accounts_ll_created_aa218a_idx'), models.Index(fields=['success'], name='accounts_ll_success_c14318_idx'), models.Index(fields=['llm_provider', 'llm_model'], name='accounts_ll_llm_pro_850a26_idx')],
            },
        ),
    ]
