# Generated by Django 5.0 on 2025-11-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_systemsettings_llm_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='llm_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google')], default='openai', help_text='The LLM provider to use for parsing text into events', max_length=50, verbose_name='LLM Provider'),
        ),
    ]
